import '../../../core/models/portfolio_models.dart';

/// Projects data service.
class ProjectsService {
  List<ProjectModel> getAllProjects() => const [
        ProjectModel(
          id: '4fc',
          name: '4FC – Rap Music Battle',
          category: 'Social Media / Entertainment',
          description:
              'A unique platform for rap music battles, allowing users to compete, vote, and engage with the hip-hop community.',
          techStack: ['Flutter', 'GetX', 'Firebase', 'Socket.IO'],
          features: [
            'Live rap battles',
            'Voting & scoring system',
            'Real-time chat',
            'Push notifications',
            'Video streaming',
          ],
          role: 'Senior Flutter Developer',
          duration: '6 months',
          gradientColors: [0xFF6366F1, 0xFF8B5CF6],
          icon: '🎤',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.fourfc',
          appStoreUrl: 'https://apps.apple.com/in/app/4fc-rap-music-battle/id6468482326',
        ),
        ProjectModel(
          id: 'onlinestage',
          name: 'Online Stage',
          category: 'Event & Jobs',
          description:
              'A platform connecting musicians and event organizers for music events, gig bookings, and job opportunities.',
          techStack: ['Flutter', 'GetX', 'REST APIs', 'Firebase'],
          features: [
            'Event booking',
            'Job board for musicians',
            'User profiles & portfolios',
            'In-app messaging',
            'Payment integration',
          ],
          role: 'Senior Flutter Developer',
          duration: '8 months',
          gradientColors: [0xFF06B6D4, 0xFF22C55E],
          icon: '🎸',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.onstages',
          appStoreUrl: 'https://apps.apple.com/in/app/online-stage-music-event-job/id6743424349',
        ),
        ProjectModel(
          id: 'partyplan',
          name: 'PartyPlan & PartyPlan Pro',
          category: 'Event Management',
          description:
              'Comprehensive event planning suite with dedicated apps for end-users (PartyPlan) and event professionals (PartyPlan Pro).',
          techStack: ['Flutter', 'GetX', 'Google Maps', 'Stripe', 'Firebase'],
          features: [
            'Vendor discovery & booking',
            'Real-time tracking',
            'Payments & invoicing',
            'Pro dashboard for vendors',
            'Event scheduling',
          ],
          role: 'Lead Flutter Developer',
          duration: '10 months',
          gradientColors: [0xFFF59E0B, 0xFFEF4444],
          icon: '🎉',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.partyplans',
          appStoreUrl: 'https://apps.apple.com/in/app/partyplans-find-event-pros/id6618148968',
        ),
        ProjectModel(
          id: 'ticketguys',
          name: 'The Ticket Guys',
          category: 'Legal-Tech',
          description:
              'Legal-tech platform featuring separate apps for clients and lawyers to manage traffic tickets and legal consultations.',
          techStack: ['Flutter', 'Clean Architecture', 'Firebase', 'REST APIs'],
          features: [
            'Case management',
            'Document upload & scanning',
            'Lawyer matching',
            'In-app chat',
            'Secure payments',
          ],
          role: 'Flutter Developer',
          duration: '7 months',
          gradientColors: [0xFF22C55E, 0xFF06B6D4],
          icon: '⚖️',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.cleanSlateLawyer.dev',
          appStoreUrl: 'https://apps.apple.com/in/app/the-ticket-guys-for-client/id6739700153',
        ),
        ProjectModel(
          id: 'vigourmedia',
          name: 'Vigour.Media',
          category: 'Social / Media',
          description:
              'Media streaming and social interaction platform with content discovery and live engagements.',
          techStack: ['Flutter', 'GetX', 'Firebase', 'Socket.IO', 'Video Player'],
          features: [
            'Video streaming',
            'Social feeds',
            'Real-time engagement',
            'Content creation',
            'Push notifications',
          ],
          role: 'Flutter Developer',
          duration: '5 months',
          gradientColors: [0xFFEC4899, 0xFF8B5CF6],
          icon: '📱',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.vigourmedia',
          appStoreUrl: 'https://apps.apple.com/in/app/vigour-media/id6446580465',
        ),
        ProjectModel(
          id: 'savorupp',
          name: 'Savor Upp',
          category: 'Food Discovery',
          description:
              'Food discovery and restaurant review application helping users find the best local dining experiences.',
          techStack: ['Flutter', 'Provider', 'Google Maps', 'REST APIs'],
          features: [
            'Location-based search',
            'Restaurant reviews',
            'Interactive maps',
            'User profiles',
            'Image galleries',
          ],
          role: 'Flutter Developer',
          duration: '6 months',
          gradientColors: [0xFFF97316, 0xFFEAB308],
          icon: '🍽️',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.savorupp',
          appStoreUrl: 'https://apps.apple.com/in/app/savor-upp/id6738163422',
        ),
        ProjectModel(
          id: 'trashtracker',
          name: 'Trash Tracker',
          category: 'Utility',
          description:
              'Utility application for tracking waste collection, scheduling pickups, and promoting environmental awareness.',
          techStack: ['Flutter', 'GetX', 'Google Maps', 'Firebase'],
          features: [
            'Live location tracking',
            'Pickup scheduling',
            'Notifications',
            'Route optimization',
            'Eco-points system',
          ],
          role: 'Senior Flutter Developer',
          duration: '4 months',
          gradientColors: [0xFF10B981, 0xFF3B82F6],
          icon: '♻️',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.trashtracker',
          appStoreUrl: 'https://apps.apple.com/in/app/trash-tracker-app/id6756876600',
        ),
        ProjectModel(
          id: 'pinvoyage',
          name: 'Pin Voyage',
          category: 'Travel & Navigation',
          description:
              'Travel companion app for pinning locations, planning voyages, and tracking journeys with real-time maps.',
          techStack: ['Flutter', 'MVVM', 'Google Maps', 'REST APIs'],
          features: [
            'Interactive travel maps',
            'Journey tracking',
            'Location saving',
            'Social sharing',
            'Offline support',
          ],
          role: 'Senior Flutter Developer',
          duration: '5 months',
          gradientColors: [0xFF3B82F6, 0xFF8B5CF6],
          icon: '🗺️',
          playStoreUrl: 'https://play.google.com/store/apps/details?id=com.app.pinvoyageapp',
          appStoreUrl: 'https://apps.apple.com/in/app/pin-voyage-app/id6758101190',
        ),
      ];

  List<String> getCategories() => const [
        'All',
        'Social Media / Entertainment',
        'Event & Jobs',
        'Event Management',
        'Legal-Tech',
        'Social / Media',
        'Food Discovery',
        'Utility',
        'Travel & Navigation',
      ];
}
